# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/extras/Build/CMake/JUCECheckAtomic.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/extras/Build/CMake/JUCEConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/extras/Build/CMake/JUCEHelperTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/extras/Build/CMake/JUCEModuleSupport.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/extras/Build/CMake/JUCEUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/extras/Build/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/extras/Build/juceaide/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/PampleTest/JUCE/modules/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/Stepper/build-universal/JUCE/tools/JUCEToolsExport.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/BasicConfigVersion-ExactVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/troycarson/Documents/JUCE\ Projects/Stepper/build-universal/CMakeFiles/cmake.verify_globs))

.NOTPARALLEL:

.PHONY: all VERIFY_GLOBS

all: VERIFY_GLOBS /Users/troycarson/Documents/JUCE\ Projects/Stepper/build-universal/CMakeFiles/cmake.check_cache

VERIFY_GLOBS:
	/opt/homebrew/bin/cmake -P /Users/troycarson/Documents/JUCE\ Projects/Stepper/build-universal/CMakeFiles/VerifyGlobs.cmake

/Users/troycarson/Documents/JUCE\ Projects/Stepper/build-universal/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/troycarson/Documents/JUCE\ Projects/Stepper -B/Users/troycarson/Documents/JUCE\ Projects/Stepper/build-universal
